import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime


class EmailSender:
    def __init__(self, gmail_address: str, app_password: str):
        self.gmail_address = gmail_address
        self.app_password = app_password

    def send(self, recipient: str, subject: str, html_body: str):
        msg = MIMEMultipart("alternative")
        msg["From"] = self.gmail_address
        msg["To"] = recipient
        msg["Subject"] = subject

        msg.attach(MIMEText(html_body, "html"))

        with smtplib.SMTP("smtp.gmail.com", 587) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(self.gmail_address, self.app_password)
            server.sendmail(self.gmail_address, recipient, msg.as_string())

    def build_digest_email(self, notes: list[dict], run_date: str = None) -> tuple[str, str]:
        if not run_date:
            now = datetime.now()
            run_date = now.strftime("%B %d, %Y")
            run_time = now.strftime("%H:%M")
        else:
            run_time = datetime.now().strftime("%H:%M")

        subject = f"Telegram Digest - {run_date} {run_time}"

        notes_html = ""
        for i, note in enumerate(notes, 1):
            topics_items = note.get("topics", [])
            topics_html = "".join(
                f'<li>{t}</li>' for t in topics_items
            )
            topics_section = ""
            if topics_html:
                topics_section = f"""
                <div class="topic-section">
                    <h4>Main Topics</h4>
                    <ul>{topics_html}</ul>
                </div>
                """
            deep_dive_items = note.get("deep_dive", [])
            deep_dive_html = "".join(
                f'<li>{item}</li>' for item in deep_dive_items
            )
            deep_dive_section = ""
            if deep_dive_html:
                deep_dive_section = f"""
                <div class="deep-dive">
                    <h4>Deep Dive Suggestions</h4>
                    <ul>{deep_dive_html}</ul>
                </div>
                """
            notes_html += f"""
            <div class="note-card">
                <h2 class="note-title">{note.get('title', 'Untitled')}</h2>
                <div class="note-meta">
                    <a href="{note.get('url', '#')}" class="note-link">{note.get('url', '')}</a>
                </div>
                <p class="note-summary">{note.get('summary', '')}</p>
                {topics_section}
                {deep_dive_section}
            </div>
            """

        html = f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body>
<div class="container">
    <div class="header">
        <h1>Telegram Digest</h1>
        <p class="date">{run_date} {run_time} &bull; {len(notes)} notes</p>
    </div>
    {notes_html if notes_html else '<p class="empty">No new notes since last run.</p>'}
    <div class="footer">
        <p>Generated by TelegramScheduler</p>
    </div>
</div>
</body>
</html>"""

        return subject, html
